### ISSUE TITLE
How to see unicorn logs

### ISSUE THREAD

**Issue by darrenhaken** [seapy/dockerfiles#7]
Hi,

I tried using the dockerfiles but unicorn comes back with a 500 status code.
How do I see the logs?

**Comment by seapy** [comment]
Default unicorn logs saved inside container(path `/app//log/unicorn.stderr.log`)
path is defined `unicorn.rb`(https://github.com/seapy/dockerfiles/blob/master/rails-nginx-unicorn-pro/unicorn.rb#L7-L8)
you will connect container using `docker exec`. http://askubuntu.com/questions/505506/how-to-get-bash-or-ssh-into-a-running-container-in-background-mode

if you want see unicorn logs by `docker log`, below commit will help you
https://github.com/rorlakr/rorla/commit/cf2fc132d8ef13b42840fbeee8525512dcc85fda
