### ISSUE TITLE
Driver btrfs failed to remove root filesystem when base container is based on old version of docker

### ISSUE THREAD

**Issue by dunnock** [seapy/dockerfiles#8]
Hi Seapy, please see the issue with old docker images https://github.com/docker/docker/issues/17429 . I like your image, but had to copy-paste whole content of your Dockerfile instead of inheriting your image. Image rebuild should fixe the issue. Cheers, Maxim

**Comment by seapy** [comment]
Thank you for your feedback.
finished rebuild images `seapy/ruby:2.2.0`, `seapy/rails-nginx-unicorn:ruby2.2.0-nginx1.8.0`, `seapy/rails-nginx-unicorn-pro:v1.0-ruby2.2.0-nginx1.8.0`

check images

**Comment by seapy** [comment]
@dunnock Can you check new image?

**Comment by dunnock** [comment]
Hi Seapy, just checked and it works like magic! Thanks

On Sat, Nov 21, 2015 at 12:05 AM, ChangHoon, Jung <notifications@github.com>
wrote:

> @dunnock <https://github.com/dunnock> Can you check new image?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seapy/dockerfiles/issues/8#issuecomment-158611349>.
>



-- 
Cheers,

Maxim

**Comment by seapy** [comment]
Great !
